In [1]:
import numpy as np 

In [11]:
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [3]:
print(a[0])

[1, 2, 3, 4]


In [10]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)
print(a.ndim)
print(a.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
(3, 4)


In [18]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
np.append(range(10), range(5))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4])

In [17]:
np.delete(a, 1)

array([ 1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [19]:
np.delete(a, 1, 1)

array([[ 1,  3,  4],
       [ 5,  7,  8],
       [ 9, 11, 12]])

In [ ]:
axis=0 baris
axis=1 kolom

In [20]:
np.delete(a, -1, axis=0)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
b_sort = np.append(range(52,55), range(21,27))

In [24]:
np.sort(b_sort)

array([21, 22, 23, 24, 25, 26, 52, 53, 54])

In [26]:
print(a)
print(a.ndim)
print(a.size)
print(a.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
12
(3, 4)


In [ ]:
reshapee=mengubah matriks

In [28]:
a.reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [29]:
a.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [30]:
a.reshape(4, 3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [31]:
np.arange(15).reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [34]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [36]:
a[np.newaxis]

array([[0, 1, 2, 3, 4]])

In [37]:
a[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [38]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', '

In [39]:
a

array([0, 1, 2, 3, 4])

In [40]:
np.expand_dims(a, axis=1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [ ]:
dims=menmabahkan dimensi array dgn fungsi


INDEXING SLICING

In [42]:
a = np.array([0,1,2,3,4,5])
a

array([0, 1, 2, 3, 4, 5])

In [43]:
a[0:3]

array([0, 1, 2])

In [44]:
a[ :]

array([0, 1, 2, 3, 4, 5])

In [45]:
a[-3:]

array([3, 4, 5])

In [46]:
a[:-1]

array([0, 1, 2, 3, 4])

In [47]:
#Slicing dengan Filter
a > 2

array([False, False, False,  True,  True,  True])

In [51]:
a[np.array([False, False, False,  True,  True,  True])]

array([3, 4, 5])

In [52]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
a[a>5]

array([ 6,  7,  8,  9, 10, 11])

In [56]:
#Disimpan sebagai kriteria agar lebih rapi
above_five = a > 8

In [57]:
a[above_five]

array([ 9, 10, 11])

In [58]:
 1 in a

True

In [59]:
a * 5

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [ ]:
list * 2 = data list diulang sebanyak dua kali

In [60]:
a % 2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]], dtype=int32)

In [61]:
a[a % 2 == 0]

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
genap = a % 2 ==0

a

In [62]:
a[(a > 2) & (a < 11) & (a % 2 !=0)]

array([3, 5, 7, 9])

In [63]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 20])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 20])

In [78]:
a_1 = np.append([1,1], [2,2], axis=0)
a_2 = np.append([3,3], [4,4], axis=0)

In [80]:
a_1


array([1, 1, 2, 2])

In [81]:
a_2

array([3, 3, 4, 4])

In [73]:
list(range(10, 100, 5))

[10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]

In [82]:
np.array([10,100,5])

array([ 10, 100,   5])

In [83]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [86]:
b = a

In [87]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [88]:
np.delete(b, -1, 0)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [89]:
b[1][-1]=100

In [90]:
 b

array([[  0,   1,   2,   3],
       [  4,   5,   6, 100],
       [  8,   9,  10,  11]])

In [91]:
print(id(a))
print(id(a.view()))

2549553483760
2549565070800


In [92]:
c = a.view()

#c sebagai backup data a, untuk memodifikasi gunakan c agar data a tetap seperti awal
#penggunaan view untuk modif data awal tanpa mengubah data awal

In [ ]:
dataframe
backup_dataframe = dataframe.copy()

BASIC OPERATIONS

In [93]:
a + 5

array([[  5,   6,   7,   8],
       [  9,  10,  11, 105],
       [ 13,  14,  15,  16]])

In [94]:
a - 5


array([[-5, -4, -3, -2],
       [-1,  0,  1, 95],
       [ 3,  4,  5,  6]])

In [97]:
a * 5 

array([[  0,   5,  10,  15],
       [ 20,  25,  30, 500],
       [ 40,  45,  50,  55]])

In [99]:
np.ones(12).reshape(3,4) * 3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [98]:
a * np.ones(12).reshape(3, 4) * 3

array([[  0.,   3.,   6.,   9.],
       [ 12.,  15.,  18., 300.],
       [ 24.,  27.,  30.,  33.]])

In [102]:
np.arange(5).sum()

10

In [103]:
np.sum(np.arange(5))

10

In [104]:
a.sum()
#Metode call

159

In [105]:
np.sum(a)
#Function call

159

In [ ]:
#Yang sering di pakai
np.sum()
np.absolute()
np.mean()
np.median()
np.add()    #
np.substract()
np.nansum()   #nilai kososng 


In [107]:
np.nanmean(np.array([np.nan, 5]))

5.0

In [108]:
np.array([np.nan, 5]).sum()   #dianggap nol

nan

In [109]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [112]:
b = np.array([[1,1], [2,2]])
b

array([[1, 1],
       [2, 2]])

In [113]:
b.sum(axis=1)

array([2, 4])

In [114]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [115]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
Broadcasting bukan operasi matriks

In [118]:
x1 = np.linspace(5, 122, num=4).reshape(2,2)
x2 = np.linspace(7, 133, num=4).reshape(2,2)


In [117]:
x1

array([[  5.,  44.],
       [ 83., 122.]])

In [119]:
x2

array([[  7.,  49.],
       [ 91., 133.]])

In [120]:
np.minimum(x1,x2)

array([[  5.,  44.],
       [ 83., 122.]])

In [121]:
np.std([x1, x2], axis=0)

array([[1. , 2.5],
       [4. , 5.5]])

In [122]:
np.min(x1)

5.0

In [124]:
np.min(x2)

7.0

In [126]:
np.random.randint(1, 100, size=10)

array([65, 85, 22, 18, 99, 59, 67, 85, 15, 34])

In [127]:
np.random.randn(3,4)

array([[-0.82573617, -0.12492896,  0.22736684, -1.31773599],
       [ 1.07633999, -1.72361447,  0.11493289, -0.3402014 ],
       [-0.92470021, -0.62147099, -0.21181184,  0.50554004]])

In [131]:
d = np.random.randn(4,3) @ a

In [132]:
d

array([[  3.3352734 ,   4.04485082,   4.75442823,  63.42966823],
       [  4.66251377,   6.40294791,   8.14338205,  80.602823  ],
       [  4.61893726,   6.9756141 ,   9.33229093, 183.28777656],
       [ 19.40742171,  22.38112215,  25.35482259, 100.25346685]])

In [133]:
a @ d

array([[   72.12265342,    87.49754255,   102.87243169,   747.93877668],
       [ 2005.10945666,  2328.16004225,  2651.21062785, 11781.8061326 ],
       [  328.31582259,   405.93382237,   483.55182216,  4168.52865376]])

In [134]:
a . dot(d)   #metode call

array([[   72.12265342,    87.49754255,   102.87243169,   747.93877668],
       [ 2005.10945666,  2328.16004225,  2651.21062785, 11781.8061326 ],
       [  328.31582259,   405.93382237,   483.55182216,  4168.52865376]])

In [135]:
d[1:3]

array([[  4.66251377,   6.40294791,   8.14338205,  80.602823  ],
       [  4.61893726,   6.9756141 ,   9.33229093, 183.28777656]])

In [136]:
d[1:4][0:3]  # depan baris, belakang kolom

array([[  4.66251377,   6.40294791,   8.14338205,  80.602823  ],
       [  4.61893726,   6.9756141 ,   9.33229093, 183.28777656],
       [ 19.40742171,  22.38112215,  25.35482259, 100.25346685]])

In [139]:
#Matriks transpose
a.transpose()  #metode call

array([[  0,   4,   8],
       [  1,   5,   9],
       [  2,   6,  10],
       [  3, 100,  11]])

In [138]:
np.transpose(a) #function call

array([[  0,   4,   8],
       [  1,   5,   9],
       [  2,   6,  10],
       [  3, 100,  11]])

In [142]:
a.reshape(4,3) #function call

array([[  0,   1,   2],
       [  3,   4,   5],
       [  6, 100,   8],
       [  9,  10,  11]])

In [141]:
a

array([[  0,   1,   2,   3],
       [  4,   5,   6, 100],
       [  8,   9,  10,  11]])

In [144]:
ndarr = np.array([[[1,2], [3,4], [5,4], [6,7]]])

In [145]:
ndarr

array([[[1, 2],
        [3, 4],
        [5, 4],
        [6, 7]]])